# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER, E, Yazi, exec, omarchy-launch-tui yazi
bindd = SUPER SHIFT, E, Nautilus, exec, uwsm-app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, omarchy-launch-or-focus Zen zen-browser
bindd = SUPER SHIFT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER, D, Discord, exec, omarchy-launch-or-focus vesktop
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"

bindd = SUPER SHIFT, Slash, Passwords, exec, uwsm-app -- bitwarden-desktop
bindd = SUPER SHIFT, T, Edt, exec, xdg-open ~/Pictures/EDT.png
bindd = CTRL SHIFT, ESCAPE, Activity, exec, omarchy-launch-tui btop


# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER, A, Claude, exec, omarchy-launch-or-focus-webapp Claude "https://claude.ai"
bindd = SUPER, C, Calendar, exec, omarchy-launch-or-focus-webapp Calendar "https://calendar.notion.so/"
bindd = SUPER, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus-webapp Music "https://music.youtube.com/"
unbind = SUPER, G
bindd = SUPER, G, Email, exec, omarchy-launch-or-focus-webapp Gmail "https://mail.notion.so/"
bindd = SUPER ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Media
bindld = ALT, N, Next track, exec, $osdclient --playerctl next
bindld = , F9, Pause, exec, $osdclient --playerctl play-pause
bindld = ALT, P, Previous track, exec, $osdclient --playerctl previous
bindeld = ,XF86AudioMicMute, Mute microphone, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle


unbind = SUPER, L
bindd = SUPER, L, Lock screen, exec, omarchy-system-lock

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

